version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./migrations:/app/migrations
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///Users.db
    depends_on:
      - redis

  redis:
    image: redis:6